services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3002:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: